apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  version: 8.5.1
  count: {{ .Values.kibana.replicaCount }}  # 1 реплика
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
          - name: SERVER_PUBLICBASEURL
            value: "http://kibana.logging.svc.cluster.local:5601"
        resources:
          requests:
            memory: {{ .Values.kibana.resources.requests.memory }}
            cpu: {{ .Values.kibana.resources.requests.cpu }}
          limits:
            memory: {{ .Values.kibana.resources.limits.memory }}
            cpu: {{ .Values.kibana.resources.limits.cpu }}
