apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.kibana.namespace }}
  labels:
    app: kibana
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Устанавливается после Elasticsearch
spec:
  replicas: {{ .Values.kibana.replicaCount }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:{{ .Values.kibana.imageTag }}
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.kibana.elasticsearchHost }}
