apiVersion: v2
name: elasticsearch-kibana
description: A Helm chart for Elasticsearch and Kibana
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: elasticsearch
    version: "8.5.1"
    repository: "https://helm.elastic.co"
  - name: kibana
    version: "8.5.1"
    repository: "https://helm.elastic.co"
