apiVersion: v1
kind: Secret
metadata:
  name: elastic-auth
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: kubernetes.io/basic-auth
stringData:
  username: elastic
  password: {{ .Values.elasticsearch_password }}
  roles: superuser
---
apiVersion: v1
kind: Secret
metadata:
  name: read-only-role
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  roles.yml: |-
    read_only:
      cluster: []
      indices:
      - names: [ 'filebeat-*' ]
        privileges: [ 'read', 'monitor' ]
      applications:
      - application: "kibana-.kibana"
        privileges:
        - "feature_dashboard.read"
        - "feature_visualize.read"
        - "feature_discover.all"
