kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6443
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        authentication:
          webhook:
            enabled: true
        authorization:
          mode: Webhook
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        authentication:
          webhook:
            enabled: true
        authorization:
          mode: Webhook
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        authentication:
          webhook:
            enabled: true
        authorization:
          mode: Webhook
