apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  namespace: {{ .Values.elasticsearch.namespace }}
  labels:
    app: elasticsearch
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Устанавливается после Job (с сертификатами)
spec:
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:{{ .Values.elasticsearch.imageTag }}
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: "single-node"
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: /usr/share/elasticsearch/config/certs/ca.crt
            - name: ELASTICSEARCH_SSL_KEY
              value: /usr/share/elasticsearch/config/certs/elasticsearch.key
            - name: ELASTICSEARCH_SSL_CERT
              value: /usr/share/elasticsearch/config/certs/elasticsearch.crt
          volumeMounts:
            - name: elasticsearch-certs
              mountPath: /usr/share/elasticsearch/config/certs
              readOnly: true
            - name: data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  volumes:
    - name: elasticsearch-certs
      secret:
        secretName: elasticsearch-master-certs
