apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  version: 8.5.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  replicaCount: {{ .Values.elasticsearch.replicaCount }}  # 3 реплики
  xpack:
    security:
      enabled: false
  auth: {}
  nodeSets:
  - name: default
    count: {{ .Values.elasticsearch.replicaCount }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi  # Если нужно, адаптировать по вашему требованию
    config:
      xpack.monitoring.collection.enabled: true
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
                memory: {{ .Values.elasticsearch.resources.requests.memory }}
              limits:
                cpu: {{ .Values.elasticsearch.resources.limits.cpu }}
                memory: {{ .Values.elasticsearch.resources.limits.memory }}
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms2g -Xmx2g"  # Пример использования памяти
