apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-master-credentials-gen
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      serviceAccountName: cert-gen-sa
      containers:
      - name: credentials-gen
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Генерация логина и пароля
          USERNAME="elastic"
          PASSWORD=$(openssl rand -base64 32)

          # Создание секрета в Kubernetes
          kubectl create secret generic elasticsearch-master-credentials \
            --namespace monitoring \
            --from-literal=username=${USERNAME} \
            --from-literal=password=${PASSWORD} \
            --dry-run=client -o yaml | kubectl apply -f -

          # Логирование сгенерированных значений
          echo "Elasticsearch credentials created:"
          echo "Username: ${USERNAME}"
          echo "Password: ${PASSWORD}" > /output/credentials.txt
        volumeMounts:
        - name: output
          mountPath: /output
      restartPolicy: OnFailure
      volumes:
      - name: output
        emptyDir: {}
