apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-master-credentials-gen
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      serviceAccountName: cert-gen-sa
      containers:
      - name: credentials-gen
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Generating Elasticsearch credentials..."
          USERNAME="elastic"
          PASSWORD=$(openssl rand -base64 32)

          echo "Username: $USERNAME"
          echo "Password: $PASSWORD"

          # Создание секрета в Kubernetes
          kubectl create secret generic elasticsearch-master-credentials \
            --namespace monitoring \
            --from-literal=username=${USERNAME} \
            --from-literal=password=${PASSWORD} \
            --dry-run=client -o yaml | kubectl apply -f -

          echo "Elasticsearch credentials successfully created."
          echo "Username: $USERNAME" > /output/credentials.txt
          echo "Password: $PASSWORD" >> /output/credentials.txt
        volumeMounts:
        - name: output
          mountPath: /output
      restartPolicy: OnFailure
      volumes:
      - name: output
        emptyDir: {}
