# Values for Prometheus and Grafana
prometheus:
  replicaCount: 1
  resources:
    limits:
      cpu: 1536m
      memory: 2Gi
    requests:
      cpu: 1536m
      memory: 2Gi
  persistence:
    enabled: true
    size: 10Gi

grafana:
  adminPassword: "admin"
  datasources:
    default:
      type: "prometheus"
      url: "http://prometheus-server.monitoring.svc.cluster.local"
  persistence:
  enabled: true
  size: 10Gi
