prometheus:
  namespace: gnida-dev
  replicaCount: 1
  resources:
    limits:
      cpu: 1536m
      memory: 2Gi
    requests:
      cpu: 1536m
      memory: 2Gi
  persistence:
    enabled: true
    storageClass: "standard"
    size: 10Gi

grafana:
  namespace: gnida-dev
  adminPassword: "admin"
  datasources:
    default:
      type: "prometheus"
      url: "http://prometheus-server.monitoring.svc.cluster.local"
  persistence:
    enabled: true # Исправлено: добавлен правильный ключ
    storageClass: "standard"
    size: 10Gi
