apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-creator-binding
  namespace: argocd
subjects:
  - kind: User
    name: admin # Укажите имя пользователя, которому нужно предоставить доступ
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: argocd-app-creator
  apiGroup: rbac.authorization.k8s.io
